# Generated by Django 2.2.4 on 2021-03-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='Show',
        ),
    ]
