# Generated by Django 2.2.4 on 2021-03-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0003_bookmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookManager',
        ),
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
